/* Crear tablas */
DROP TABLE IF EXISTS "public"."FACT_DELITOS";
DROP TABLE IF EXISTS "public"."DIM_TIEMPO";
DROP TABLE IF EXISTS "public"."DIM_TIPO";
DROP TABLE IF EXISTS "public"."DIM_SUBTIPO";
DROP TABLE IF EXISTS "public"."DIM_UBICACION";

CREATE TABLE "public"."FACT_DELITOS" (
	"ID_TIEMPO" INT NOT NULL,
	"ID_TIPO" INT NOT NULL,
	"ID_SUBTIPO" INT NOT NULL,
	"ID_UBICACION" INT NOT NULL,
	"DS_USO_ARMA" VARCHAR(2) NOT NULL,
	"DS_USO_MOTO" VARCHAR(2) NOT NULL,
	"CANTIDAD" INT NOT NULL
);

CREATE TABLE "public"."DIM_TIEMPO" (
	"ID_TIEMPO" SERIAL PRIMARY KEY,
	"ANIO" INT NOT NULL,
	"ID_MES" INT NOT NULL,
	"DS_MES" VARCHAR(50) NOT NULL,
	"ID_DIA_SEMANA" INT NOT NULL,
	"DS_DIA_SEMANA" VARCHAR(50) NOT NULL,
	"DIA_MES" INT NOT NULL,
	"HORARIO" INT NOT NULL
);

CREATE TABLE "public"."DIM_TIPO" (
	"ID_TIPO" SERIAL PRIMARY KEY,
	"DS_TIPO" VARCHAR(50) NOT NULL
);

CREATE TABLE "public"."DIM_SUBTIPO" (
	"ID_SUBTIPO" SERIAL PRIMARY KEY,
	"DS_SUBTIPO" VARCHAR(50) NOT NULL
);

CREATE TABLE "public"."DIM_UBICACION" (
	"ID_UBICACION" SERIAL PRIMARY KEY,
	"DS_BARRIO" VARCHAR(100) NOT NULL,
	"DS_CIUDAD_BARRIO" VARCHAR(100) NOT NULL,
	"ID_COMUNA" INT NOT NULL,
	"DS_COMUNA" VARCHAR(100) NOT NULL
);

/* Establecer relaciones entre la Fact y las dimensiones*/
ALTER TABLE "public"."FACT_DELITOS"
ADD CONSTRAINT FK_FACT_DELITOS_ID_TIEMPO
FOREIGN KEY ("ID_TIEMPO") REFERENCES "public"."DIM_TIEMPO" ("ID_TIEMPO");

ALTER TABLE "public"."FACT_DELITOS"
ADD CONSTRAINT FK_FACT_DELITOS_ID_TIPO
FOREIGN KEY ("ID_TIPO") REFERENCES "public"."DIM_TIPO" ("ID_TIPO");

ALTER TABLE "public"."FACT_DELITOS"
ADD CONSTRAINT FK_FACT_DELITOS_ID_SUBTIPO
FOREIGN KEY ("ID_SUBTIPO") REFERENCES "public"."DIM_SUBTIPO" ("ID_SUBTIPO");

ALTER TABLE "public"."FACT_DELITOS"
ADD CONSTRAINT FK_FACT_DELITOS_ID_UBICACION
FOREIGN KEY ("ID_UBICACION") REFERENCES "public"."DIM_UBICACION" ("ID_UBICACION");
